server:
  port: 9095
spring:
  application:
    name: userEvent

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "*"
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

    consumer:
      bootstrap-servers: localhost:9092
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5432/shiroyadb
    username: postgres
    password: shiroya
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true